# Generated by Django 5.0 on 2023-12-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0003_sudoku_is_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='niveau',
            field=models.CharField(default='easy', max_length=10),
        ),
    ]
